### ISSUE TITLE
css for cyno/cloak/entosis cell doesn't carry over to navigated month...

### ISSUE THREAD

**Issue by Nuramori** [Salvoxia/cynoCloakMod#1]
The mod works great on the first/home page.  When you navigate to a previous month, using "Navigation" in the menu list, mods/cynoCloakMod/cynoCloakMod.css is listed in the header but not loaded, and therefore the cell format breaks.

Example: http://kb.tiod.wtf/index.php/home/2017/4/
vs the home page: http://kb.tiod.wtf/?a=home

**Comment by Salvoxia** [comment]
Hi,

thanks for reporting.
This issue should now be fixed with the [current release 0.9.1](https://github.com/Salvoxia/cynoCloakMod/releases/tag/v0.9.1).

Please report back whether this issue is now fixed for you.

Best Regards,
Salvoxia

**Comment by Nuramori** [comment]
Works perfectly.  Thank you Sir.

(I came across another issue in Fleet battles, so I'll post the sql error there :p)
